#!/usr/bin/env bash
# Configuration on server side NGINX
apt-get -y update
apt-get -y install nginx

#Save the string Holberton School to the root index
echo "Holberton School" > /var/www/html/index.nginx-debian.html

# Add directive rewrite to default file
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me http://www.holbertonschool.com permanent;" /etc/nginx/sites-available/default

# Save the string Ceci n'est pas une page to error page 404
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

# Add directive error_page to default file
sed -i "/server_name _;/ a\\\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}" /etc/nginx/sites-available/default


# Add directive add_header to the default file
sudo sed -i "/location \/ {/ a\\\t\tadd_header X-Served-By \$hostname;" /etc/nginx/sites-available/default

# Restart the web server after set configurations
service nginx restart
