#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with localhost 127.0.0.2 and facebook.com 8.8.8.8.
cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
sed -i '/127.0.0.2/a 8.8.8.8 facebook.com' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
